vs2022/starwars-game/starwars.game.Web.UI/Models/CheckPoint.cs
namespace starwars.game.Web.UI.Models
{
    public class CheckPoint
    {
        #region Properties
        public int GameId { get; set; }

        public int PersoPointsDeVie { get; set; }
        #endregion
    }
}

vs2022/starwars-game/starwars.game.Web.UI/Models/DefaultDbContext.cs
using Microsoft.EntityFrameworkCore;
using starwars.game.Web.UI.Models;
using System.Collections.Generic;

namespace WebApplication1.Models
{
	public class DefaultDbContext : DbContext
	{
		public DefaultDbContext(DbContextOptions options) : base(options)
		{
		}

		protected DefaultDbContext()
		{
		}

		/// <summary>
		/// C'est une Liste et elle sera connectée à une table en bdd
		/// </summary>
		public DbSet<Game> Games { get; set; }
	}
}

vs2022/starwars-game/starwars.game.Web.UI/Models/ErrorViewModel.cs
namespace starwars.game.Web.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

vs2022/starwars-game/starwars.game.Web.UI/Models/Game.cs
namespace starwars.game.Web.UI.Models
{
    public class Game
    {
        public int Id { get; set; } = 0;

        //public List<CheckPoint> CheckPointList { get; set; } = new();

        public DateTime DateCreation { get; set; }

        public DateTime DateDebut { get; set; }
    }
}

vs2022/starwars-game/starwars.game.Web.UI/Models/GameAddViewModel.cs
namespace starwars.game.Web.UI.Models
{
	public class GameAddViewModel
	{
        public  Game Game { get; set; }
    }
}

vs2022/starwars-game/starwars.game.Web.UI/Models/ListGame.cs
namespace starwars.game.Web.UI.Models
{
    public class ListGame
    {
        public List<Game> Liste1 { get; set; }
        public List<CheckPoint> Liste2 { get; set; }
    }
}

vs2022/starwars-game/starwars.game.Web.UI/Controllers/GameController.cs
using Microsoft.AspNetCore.Mvc;
using starwars.game.Web.UI.Models;
using WebApplication1.Models;

namespace starwars.game.Web.UI.Controllers
{
    public class GameController : Controller
    {
		private readonly DefaultDbContext context;
		// Parceque j'ai ajouté la ligne AddDbContext dans le routeur
		// ici on va récupérer une instance deja prete
		public GameController(DefaultDbContext context)
		{
			this.context = context;
		}
		public IActionResult Index()
        {
            List<Game> list = new()
            {
                new() {  Id= 1, DateCreation = DateTime.Now, DateDebut = DateTime.Now },
                new() {  Id= 2, DateCreation = DateTime.Now, DateDebut = DateTime.Now }
            };
            List<CheckPoint> list2 = new()
            {
                new() { GameId = 1, PersoPointsDeVie = 90 },
                new() { GameId = 1, PersoPointsDeVie = 85 },
                new() { GameId = 2, PersoPointsDeVie = 75 },
                new() { GameId = 2, PersoPointsDeVie = 50 },
                new() { GameId = 2, PersoPointsDeVie = 20 }

            };
            return View("Index", new ListGame{ Liste1 = list, Liste2 = list2 });
        }

		[HttpGet]
		public IActionResult Add()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Add(GameAddViewModel item)
		{
			this.context.Games.Add(item.Game);
			this.context.SaveChanges();

			return RedirectToAction("Index");
		}
	}
}

vs2022/starwars-game/starwars.game.Web.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using starwars.game.Web.UI.Models;
using System.Diagnostics;

namespace starwars.game.Web.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

vs2022/starwars-game/starwars.game.Web.UI/Views/Game/Add.cshtml
<h3>Créer une nouvelle partie !</h3>
<form asp-action="Add" asp-controller="Game" method="post">
    <label for="DateDeCreation">Date de création</label>
    <input type="text" name="DateDeCreation" value="@DateTime.Now" />
    <input type="text" hidden name="DateDeDebut" value="@DateTime.Now" />
    <button type="submit">Créer</button>
</form>

vs2022/starwars-game/starwars.game.Web.UI/Views/Game/Index.cshtml
<h1>Liste des games</h1>

@if (Model.Liste1.Count > 0)
{
    <h2>Tableau contenant les parties</h2>
    <table class="table table-bordered" style="width:500px;">
        <thead>
            <tr class="table-active">
                <th>Numéro de partie</th>
                <th>Date de début de partie</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in this.Model.Liste1)
            {
                <tr>
                    <td>@(item.Id)</td>
                    <td>@(item.DateDebut)</td>
                </tr>
            }
        </tbody>
    </table>

    <h2 class="mt-3">Tableau contenant les checkpoints pour chaque game</h2>
    <table class="table table-bordered" style="width:500px;">
        <thead>
            <tr class="table-active">
                <th>Numéro de partie</th>
                <th>Point de vie du personnage</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Liste2)
        {
            <tr>
                <td>@(item.GameId)</td>
                <td>@(item.PersoPointsDeVie)</td>
            </tr>
        }
        </tbody>
    </table>
}
else
{
    <i>Aucune partie commencée</i>
}

vs2022/starwars-game/starwars.game.Web.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

vs2022/starwars-game/starwars.game.Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - starwars.game.Web.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/starwars.game.Web.UI.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">starwars.game.Web.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Liste des parties</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Add">Ajouter une partie</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - starwars.game.Web.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>